name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, macos-12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Brew insatall qt6
        run: brew install qt

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          options: |
            CMAKE_BUILD_TYPE=Release
          build-args: --config Release
