name: Release mac

on:
  release:
    types: [created] # Runs when a new release is created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Brew insatall qt6
        run: brew install qt

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          options: |
            CMAKE_BUILD_TYPE=Release
          build-args: --config Release

      - name: Package with CPack
        run: |
          cd build
          cpack
      - name: Find .app Bundle
        run: |
          echo "Searching for .app..."
          find build -name "*.app"

      - name: Verify .app Structure
        run: |
          APP_PATH=$(find build -name "*.app" | head -n 1)
          echo "Checking structure of $APP_PATH"

      - name: Validate Info.plist
        run: |
          APP_PATH=$(find build -name "*.app" | head -n 1)
          plutil -lint "$APP_PATH/Contents/Info.plist"

      - name: List Linked Libraries
        run: |
          APP_PATH=$(find build -name "*.app" | head -n 1)
          EXECUTABLE=$(ls "$APP_PATH/Contents/MacOS/")
          echo "Checking linked libraries for $EXECUTABLE"
          otool -L "$APP_PATH/Contents/MacOS/$EXECUTABLE"

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: build/package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
